package tn.esprit.piproject.Entities;

public enum TypeRec {
    ACCESS_TO_INTERNSHIP_OPPORTUNITIES,
    APPLICATION_PROCESS,
    MONITORING_OF_INTERNSHIPS,
    ADMINISTRATIVE_AUTOMATION,
    MATCHING_OF_INTERNSHIP_OFFERS_AND_QUALIFICATIONS,
    TRANSPARENCY_AND_VISIBILITY,
    CONTINUOUS_IMPROVEMENT_OF_INTERNSHIP_EXPERIENCES,
    COMPLIANCE_WITH_REGULATORY_AND_ACCREDITATION_REQUIREMENTS
}
